### ISSUE TITLE
Incompatibility with Safari iOS

### ISSUE THREAD

**Issue by phinoda** [flekschas/regl-scatterplot#90] opened 2022-10-17 09:00 UTC
Hi Fritz,
I've been testing the scatterplot on the following touchable devices:
- iPad (Safari, iOS 15.5)
- iPhoneX (Safari,  iOS 15.5)
It seems the dots cannot be rendered on touchable device. Also, it's not possible to pan the canvas.
The dots do render on Chrome device simulator (Chrome version 106.0.5249.119), but still can't pan.

Thoughts?

Thanks!

**Comment by flekschas** [comment] 2022-10-17 19:53
Mhhh this is odd. I am not sure from the top of my head why the interactions don't work but it sounds like the issue is related to the Safari on iOS. It might be that Safari on iOS does not support or disables certain WebGL extensions required to render the scatter plot.

To be frank, when I created the library I wasn't really considering mobile devices much as I was focusing on large-scale data exploration. Anyway, thanks for bringing this up. I'll have to test this myself a little bit.

**Comment by flekschas** [comment] 2022-10-22 19:59
regl-scatterplot does not use WebGL 2. It's using WebGL 1. That's why I believe it might be related to the webgl extensions. The library uses the [following four GL extensions](https://github.com/flekschas/regl-scatterplot/blob/master/src/constants.js#L19-L24):
1. OES_texture_float
2. OES_element_index_uint
3. WEBGL_color_buffer_float
4. EXT_float_blend
I've been out all week and haven't had a chance to do any testing but https://webglreport.com/ could help us. When I open the website, it turns out that `EXT_float_blend` is not a supported extension. That might be the reason why regl-scatterplot is not rendering in Safari on iOS

**Comment by flekschas** [comment] 2022-10-22 20:05
On macOS, Safari does list [EXT_float_blend](https://www.khronos.org/registry/webgl/extensions/EXT_float_blend) as a supported extension.

Also weird, according to https://developer.mozilla.org/en-US/docs/Web/API/EXT_float_blend#browser_compatibility the extension is supported by iOS so maybe webgl-report is just not working correctly and that the error is caused by something else. I'll have to do some remote debugging so find out what errors are thrown

**Comment by flekschas** [comment] 2022-10-23 18:29
Okay so the sad news is that `EXT_float_blend` is not supported, which is why regl-scatterplot does not render on Safari iOS.

As a sanity, I've also tested https://observablehq.com/@rreusser/selecting-the-right-opacity-for-2d-point-clouds which relies on `EXT_float_blend` too. That pages also does not load in Safari iOS unfortunately.

I don't think there's anything I can do actively to fix this issue as the float blending extension is needed to support a feature. Hopefully Apple will bring back `EXT_float_blend` support on iOS...

Meanwhile, I've opened a ticket with MDN to indicate that Safari on iOS does not support this extension starting with iOS version 16: https://github.com/mdn/browser-compat-data/issues/18061

**Comment by phinoda** [comment] 2022-10-31 08:07
So I've done a bit testing about your demo site, the 2d point clouds for sanity and my own implementation.
Here's my result:
<img width="521" alt="Screen Shot 2022-10-31 at 4 04 05 AM" src="https://user-images.githubusercontent.com/10699942/198960606-dbb1250b-171e-4d7b-8b83-cd1397fd0360.png">
What intrigued me is that:
1. Correct me if I'm wrong, but I assume Chrome on iOS would work but I've got no luck, and
2. My implementation somehow renders on MacOS Safari with the other two not working 🤯

**Comment by flekschas** [comment] 2022-10-31 12:40
> Correct me if I'm wrong, but I assume Chrome on iOS would work but I've got no luck, and

No. As far as I know, on iOS you really only have one browser rendering engine, which is WebKit. Chrome on iOS is really only a different UI on top of the same rendering engine that's powering Safari. So I am not surprised that it's not working on iOS Chrome.

> My implementation somehow renders on MacOS Safari with the other two not working 🤯

This seems to be a different issue and unrelated to Safari iOS. regl-scatterplot works fine for me in Safari (v16) on macOS (v12.6). Could you open a new issue and provides some background information like the versions of Safari and macOS, and which demo you have tested? Also, have you checked the web console for any error messages?

**Comment by flekschas** [comment] 2022-10-31 12:44
FYI, MDN confirmed my suspicion that Safari iOS is not supporting `EXT_float_blend` anymore and [merged my PR](https://github.com/mdn/browser-compat-data/issues/18061). Hence, there is not much one can do at the moment. The only option I see at this point is to remove the usage of `EXT_float_blend` on Safari iOS. However, I am not sure when I find time to get to it. In the meantime, I might add a visual indicator so users know when regl-scatterplot is expected to not work.

**Comment by phinoda** [comment] 2022-11-01 08:53
> No. As far as I know, on iOS you really only have one browser rendering engine, which is WebKit. Chrome on iOS is really only a different UI on top of the same rendering engine that's powering Safari. So I am not surprised that it's not working on iOS Chrome.

Makes sense!

> This seems to be a different issue and unrelated to Safari iOS. regl-scatterplot works fine for me in Safari (v16) on macOS (v12.6). Could you open a new issue and provides some background information like the versions of Safari and macOS, and which demo you have tested? Also, have you checked the web console for any error messages?

I've opened a new issue [here](https://github.com/flekschas/regl-scatterplot/issues/92).

**Comment by flekschas** [comment] 2022-11-11 22:43
I am closing this issue for now as [MDN confirmed](https://developer.mozilla.org/en-US/docs/Web/API/EXT_float_blend#browser_compatibility) that Safari on iOS simple does not support the required WebGL extension anymore. This is unfortunate but there isn't really anything I can do.

To indicate whether all WebGL extensions are supported or not I've added a prop called `isSupported` in v1.3.2. Using that prop the demos will display an error message accordingly. E.g., see the screenshot below

![IMG_A3A56A6264DB-1](https://user-images.githubusercontent.com/932103/201440626-f91b44ae-fdfb-4e5f-8b97-b690f145ec7b.jpeg)

**Closed by flekschas** 2022-11-11 22:43 UTC
Labels: bug

**Comment by phinoda** [comment] 2022-11-11 22:52
Sounds great. Thanks for adding the prop @flekschas !!

**Comment by fspoettel** [comment] 2024-12-12 15:25
Hi, small update here: regl-scatterplot works in iOS 18 again 🎉

**Comment by phinoda** [comment] 2024-12-14 12:21
Thanks for keeping me posted Felix! I will give it a try the first thing when I arrive home and let you know how it works :)

-Quinn
