### ISSUE TITLE
Mouse offset when selecting or lasso-ing points

### ISSUE THREAD

**Issue by mvoodarla** [flekschas/regl-scatterplot#41] opened 2021-03-24 23:53 UTC
Hi Fritz - amazing library, I was trying to find something that was responsive and could handle many data points and this is exactly what I needed. However, I'm trying to integrate this with my react app and I'm noticing an offset in mouse position when I try to select points or use the lasso. Do you have any idea why this might be and/or examples of using this within a basic react app?

**Comment by flekschas** [comment] 2021-03-25 00:04
Thanks for giving regl-scatterplot a try and sorry about the issue you're running into. May I ask which version you're using? I recently discovered a bug in the mouse position when the webpage was scrollable. However, it should have been fixed in v0.16.2.

Otherwise I don't think that React has anything to do with the offset. My guess is that it's somehow related to how I retrieve the mouse position. To get a better sense of how you're using regl-scatterplot, could you provide some more details or maybe even a simple demo?

**Comment by mvoodarla** [comment] 2021-03-25 00:14
Yeah, sure I'm using v0.17.0 right now. I've attached a code snippet below of the React component I'm trying to use it in. This component exists within a React fragment.

```
import React, { useEffect, useRef } from 'react';

import createScatterplot from 'regl-scatterplot';

export default function ZoomGraph() {
  const canvasRef = useRef(null);
  let canvas;
  let scatterplot;
  useEffect(() => {
    canvas = canvasRef.current;
    scatterplot = createScatterplot({
      canvas
    });

    scatterplot.set({ backgroundColor: '#00ff00' }); // hex string
    scatterplot.set({ backgroundColor: [255, 0, 0] }); // rgb array
    scatterplot.set({ backgroundColor: [255, 0, 0, 1.0] }); // rgba array
    scatterplot.set({ backgroundColor: [1.0, 0, 0, 1.0] }); // normalized rgba

    // Color by
    scatterplot.set({ colorBy: 'category' });

    // Set color map
    scatterplot.set({
      pointColor: ['#ff0000', '#00ff00', '#0000ff'],
      pointColorActive: ['#ff0000', '#00ff00', '#0000ff'], // optional
      pointColorHover: ['#ff0000', '#00ff00', '#0000ff'], // optional
    });

    // Set base opacity
    scatterplot.set({ opacity: 0.5 });

    // Set the width of the outline of selected points
    scatterplot.set({ pointOutlineWidth: 2 });

    // Set the base point size
    scatterplot.set({ pointSize: 10 });

    // Set the additional point size of selected points
    scatterplot.set({ pointSizeSelected: 2 });
    scatterplot.set({ showRecticle: true, recticleColor: [1, 0, 0, 0.66] });
    scatterplot.draw([
      [0.2, -0.1, 0, 0.1337],
      [0.3, 0.1, 1, 0.3371],
      [-0.9, 0.8, 2, 0.3713],
    ]);
  }, []);
  return (
    <>
      <canvas ref={canvasRef} />
    </>
  );
}
```

**Comment by mvoodarla** [comment] 2021-03-25 04:51
I also did notice that the position of the selection or lasso seems to be most "accurate" in its position on the top left of the canvas and tends to change proportionately to the distance from there. One example is that the lasso seems to select the entire width or height of the canvas by the time I drag my cursor halfway through. Not sure if there's anything this hints to but just wanted to note it here.

**Comment by flekschas** [comment] 2021-03-25 13:00
Thanks for he note. Just to clarify, you mean this happens when you use it within your React app or also on the live demos?

I will take a look but currently are super times so I don't know when I get to it. If you have the time, it would help me a lot if you could setup a live demo of your react app for me to play with, but no pressure.

**Comment by mvoodarla** [comment] 2021-03-25 18:45
This is when I try it within my own React app. Here is a live [codesandbox](https://codesandbox.io/s/beautiful-elgamal-pwtg9) demo. Thanks for the responsiveness on this issue, it really means a lot!

**Comment by flekschas** [comment] 2021-03-25 22:46
Thanks! Will take a look as soon as I find some free time.

**Comment by mvoodarla** [comment] 2021-03-25 23:40
Great, thanks! Just to confirm, you are seeing the same bug I mentioned, right?

**Comment by flekschas** [comment] 2021-03-26 02:27
Mhhh not really unfortunately 😅  For me all the mouse interactions work as expected. Could you record maybe a gif? This seems to be quite a tricky bug.

**Comment by mvoodarla** [comment] 2021-03-26 02:37
Oh wow, that is really tricky then. Here is a [link](https://makeagif.com/i/Vq3KQA) to a gif of the issue. I experience the same issue on Chrome and Opera.

**Comment by mvoodarla** [comment] 2021-03-26 17:31
Hey Fritz - just wanted to give you an update on this issue. I ended up using the same CSS properties that were specified in [your example](https://github.com/flekschas/regl-scatterplot/blob/master/example/index.html) and now it works! Not sure if you want to resolve this issue and you intend for everyone to use similar properties or whether you intend for it to work on a canvas with no added properties.

Regardless, I think this is the only scatterplot library out there that is easy to use and can handle millions of points in a light-weight manner so props to that!

**Comment by flekschas** [comment] 2021-03-26 18:07
I would love to find out what caused the issue because I cannot reproduce it. Please see below how [your example](https://codesandbox.io/s/beautiful-elgamal-pwtg9) looks and interacts for me:

![Mar-26-2021 14-01-15](https://user-images.githubusercontent.com/932103/112674096-e7511f00-8e3b-11eb-8806-ca2f8718ba3a.gif)

Now saying that you had to explicitly apply certain CSS rules. That makes me wonder if there are certain styles applied by a third party in your or my case that leads to the different behavior.

Could you tell me which CSS rules fixed the issue for you? Also, when you inspect the canvas element from https://codesandbox.io/s/beautiful-elgamal-pwtg9 **without** applying any CSS styles, what kind of default styles are you seeing in your browser? In my case it's only `font-family: sans-serif;` and `text-align: center;`:

![Screen Shot 2021-03-26 at 2 05 54 PM](https://user-images.githubusercontent.com/932103/112674560-752d0a00-8e3c-11eb-8be0-87325f90c012.png)

One idea I have is that maybe a browser plugin interferes somehow with the styling.

**Comment by mvoodarla** [comment] 2021-03-26 18:23
Hmm that's an interesting point but it seems like the default styling on my browser is the same as yours when I inspect element. What fixed my issue was `style={{ width: "100%", height: "100%" }}` . This is still a mystery to me so I'll continue investigating and will get back to you.

**Comment by flekschas** [comment] 2021-03-26 18:35
Interesting. If you don't apply the styles, how big the `canvas` element and where is it positioned? For me the canvas is set to 300x150 and looks as follows. Interactions again work as expected.

![Screen Shot 2021-03-26 at 2 34 22 PM](https://user-images.githubusercontent.com/932103/112677756-7fe99e00-8e40-11eb-8bfe-6a14313a2c30.png)

**Comment by mvoodarla** [comment] 2021-03-26 18:44
For me, it is 600x300 by default.

<img width="675" alt="Screen Shot 2021-03-26 at 11 42 29 AM" src="https://user-images.githubusercontent.com/11367688/112678726-85d38500-8e28-11eb-80cb-110edc3b5e28.png">

**Comment by flekschas** [comment] 2021-03-26 19:03
Ha! I found the issue. It's related to the `devicePixelRatio`. I can reproduce the error when I open up the example on my other monitor.

It seems like by default (when the canvas does not have any width or height) and the monitor has a `devicePixelRatio > 1` then the default width represents device pixels rather than the CSS pixels.

Should be easy to fix. Thanks for spending all the time and helping out finding the root cause for the issue.

**Comment by flekschas** [comment] 2021-03-26 19:04
Also, as you already found out, you can temporarily fix this by simply specifying a width and height for the canvas element.

**Comment by mvoodarla** [comment] 2021-03-26 19:07
Oh wow, that's pretty obscure but great that you figured that out. When I specify height and width though, I tend to get a more laggy experience. Is the fix you mentioned something you'll be able to pack into a new version relatively quickly? Again, thanks for your help as well!

**Comment by flekschas** [comment] 2021-03-26 19:44
Can you maybe specify what you mean by a laggy experience? I haven't experience anything like that.

I will work on a fix but can't promise any release date because of a lot of other work. But the fix wouldn't be different from assigning a reasonable default height/width or inferring the height/width from a parent element, so you can already implement it by specifying a height.

**Closed** 2021-04-02 01:14 UTC
Labels: bug

**Comment by flekschas** [comment] 2021-04-02 01:17
Issue should be fixed. By default (`width = 'auto'` and `height = 'auto'`)  the canvas will now stretch to 100% of the parent container unless you specify a fixed width/height.

Note, you still are in charge of determining how to position the canvas element. I suggest wrapping the canvas element with a `div` or so and controlling the size via this wrapper element.
