### ISSUE TITLE
Demos do not render in Safari v14 due to missing BigInt64Array support

### ISSUE THREAD

**Issue by phinoda** [flekschas/regl-scatterplot#92] opened 2022-11-01 08:51 UTC
https://flekschas.github.io/regl-scatterplot/ <- this demo is not rendering on some MacOS Safari versions.
Safari version: 14.0.3
MacOS version: 11.2

**Comment by flekschas** [comment] 2022-11-03 02:06
Do you see any errors in the web console?

Unfortunately I cannot reproduce the issue. I've tested the following versions and in both cases the demo works for me:
1. macOS v11.6.1 with Safari v15.1
2. macOS v12.6 with Safari v16

**Comment by phinoda** [comment] 2022-11-03 23:58
I get this:
ReferenceError: Can't find variable: BigInt64Array
<img width="964" alt="Screen Shot 2022-10-20 at 9 40 20 PM" src="https://user-images.githubusercontent.com/10699942/199856982-a3e66982-82ac-4137-b887-49ba5a168f93.png">

**Comment by phinoda** [comment] 2022-11-03 23:58
I get this:
ReferenceError: Can't find variable: BigInt64Array
<img width="1322" alt="Screen Shot 2022-11-03 at 7 57 33 PM" src="https://user-images.githubusercontent.com/10699942/199857028-23f76910-0130-43bf-91ec-e56153b9c05d.png">

**Comment by flekschas** [comment] 2022-11-05 14:33
This error is expected as Safari didn't add `BigInt64Array` support until version 15: https://caniuse.com/?search=bigint64array.

However, regl-scatterplot does not directly use `BigInt64Array`. Apache-Arrow does (which I am using for a demo) My guess is that this is causes all demos to fail for you.

**Comment by flekschas** [comment] 2022-11-05 14:35
I could break up the demos so that only https://flekschas.github.io/regl-scatterplot/multiple-instances.html relies on Apache Arrow (all the other demos do not use Apache Arrow)

**Comment by phinoda** [comment] 2022-11-09 00:28
> This error is expected as Safari didn't add `BigInt64Array` support until version 15: https://caniuse.com/?search=bigint64array.
> 
> However, regl-scatterplot does not directly use `BigInt64Array`. Apache-Arrow does (which I am using for a demo) My guess is that this is causes all demos to fail for you.

Makes sense. I'm actually reluctant to upgrade my system as Apple is doing an ever worse job... breaking up the demo sounds like a great idea :)

**Comment by flekschas** [comment] 2022-11-11 22:45
I've updated the demos such that `apache-arrow` is only included in https://flekschas.github.io/regl-scatterplot/multiple-instances.html.

Can you confirm that you can load other demos now? E.g., https://flekschas.github.io/regl-scatterplot/. You might have to do a hard refresh (i.e., when you open the web console you should see a message saying `Scatterplot v1.3.2`)

**Comment by phinoda** [comment] 2022-11-11 22:56
I'm still just seeing the error message ("Unfortunately, your browser does not support all WebGL extensions required by regl-scatterplot") after hard refreshing Safari.

**Comment by flekschas** [comment] 2022-11-12 02:05
That's a different error. The above `Can't find variable: BigInt64Array` issue should only appear when you go to https://flekschas.github.io/regl-scatterplot/multiple-instances.html but not at https://flekschas.github.io/regl-scatterplot/.

Apart from that I highly recommend to update Safari to version 14.1 (currently the latest version on macOS Big Sur). Regl-scatterplot works fine on that version in my tests.

Apart from that, I updated the modal that say "Unfortunately, your browser does not support..." to be closable. In Safari 13.1, the scatter plot renders even though some GL extensions are not supported. This might be the same situation in Safari 14.0.1.

Thanks for bringing the issue with the lacking support for BigInt64Array to my attention. Nevertheless, I am closing this ticket now because I am not going to spent time on a work-around for the lacking BigInt64Array support for a two-year old browser.

**Closed by flekschas** 2022-11-12 02:05 UTC
Labels: bug
